const fs = require('fs');
const path = require('path');

// Configuration
const IMAGES_DIR = path.join(__dirname, '../public/assets/images/gallery');
const OUTPUT_FILE = path.join(__dirname, '../src/data/galleryData.ts');

// Ensure directory exists
if (!fs.existsSync(IMAGES_DIR)) {
  console.log(`Creating directory: ${IMAGES_DIR}`);
  fs.mkdirSync(IMAGES_DIR, { recursive: true });
}

// Helper to format title from filename
const formatTitle = (filename) => {
  const nameWithoutExt = filename.split('.').slice(0, -1).join('.');
  return nameWithoutExt
    .split(/[-_]/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

// Helper to guess category from filename
const guessCategory = (filename) => {
  const lowerName = filename.toLowerCase();
  if (lowerName.includes('luxury') || lowerName.includes('gold') || lowerName.includes('diamond')) return 'luxury';
  if (lowerName.includes('classic') || lowerName.includes('french') || lowerName.includes('nude')) return 'classic';
  if (lowerName.includes('modern') || lowerName.includes('geo') || lowerName.includes('abstract')) return 'modern';
  if (lowerName.includes('art') || lowerName.includes('flower') || lowerName.includes('paint')) return 'artistic';
  if (lowerName.includes('christmas') || lowerName.includes('summer') || lowerName.includes('winter')) return 'seasonal';
  if (lowerName.includes('wedding') || lowerName.includes('bridal')) return 'luxury';
  return 'artistic'; // Default
};

// Helper to generate tags
const generateTags = (filename, category) => {
  const tags = [category];
  const lowerName = filename.toLowerCase();
  
  const keywords = [
    'gold', 'french', 'floral', 'geometric', 'nude', 'bold', 'sparkle', 
    'ombre', 'matte', 'glossy', 'wedding', 'summer', 'winter', 'fall', 
    'spring', 'dark', 'light', 'colorful', 'minimal'
  ];

  keywords.forEach(keyword => {
    if (lowerName.includes(keyword)) {
      tags.push(keyword);
    }
  });

  return [...new Set(tags)]; // Unique tags
};

// Read images
try {
    console.log('Scanning for images...');
    const files = fs.readdirSync(IMAGES_DIR);
    
    // Filter for image files
    const imageFiles = files.filter(file => {
        const ext = path.extname(file).toLowerCase();
        return ['.jpg', '.jpeg', '.png', '.webp', '.gif'].includes(ext);
    });

    console.log(`Found ${imageFiles.length} images.`);

    const galleryImages = imageFiles.map((filename, index) => {
        const title = formatTitle(filename);
        const category = guessCategory(filename);
        return {
            id: index + 1,
            filename: filename,
            title: title,
            description: `${title} - Professional nail art design`,
            category: category,
            featured: index < 6, // Feature first 6 by default
            tags: generateTags(filename, category),
            dateAdded: new Date().toISOString().split('T')[0]
        };
    });

    const fileContent = `// Gallery Data Management
// This file is auto-generated by scripts/generate-gallery.js
// Do not edit manually if you plan to use the script.

export interface GalleryImage {
  id: number;
  filename: string;
  title: string;
  description: string;
  category: 'luxury' | 'classic' | 'modern' | 'artistic' | 'seasonal';
  featured?: boolean;
  tags?: string[];
  dateAdded?: string;
}

export const galleryImages: GalleryImage[] = ${JSON.stringify(galleryImages, null, 2)};

// Helper functions for gallery management
export const getImagePath = (filename: string): string => {
  return \`\${process.env.PUBLIC_URL}/assets/images/gallery/\${filename}\`;
};

export const getFeaturedImages = (): GalleryImage[] => {
  return galleryImages.filter(image => image.featured);
};

export const getImagesByCategory = (category: string): GalleryImage[] => {
  if (category === 'all') return galleryImages;
  return galleryImages.filter(image => image.category === category);
};

export const getImagesByTag = (tag: string): GalleryImage[] => {
  return galleryImages.filter(image => 
    image.tags?.includes(tag.toLowerCase())
  );
};

export const getRecentImages = (count: number = 6): GalleryImage[] => {
  // Since we don't have real dates in filenames, we just take the last added (highest ID) or just logic from array
  return [...galleryImages].reverse().slice(0, count);
};

export const galleryCategories = [
  { value: 'all', label: 'All Designs' },
  { value: 'luxury', label: 'Luxury' },
  { value: 'classic', label: 'Classic' },
  { value: 'modern', label: 'Modern' },
  { value: 'artistic', label: 'Artistic' },
  { value: 'seasonal', label: 'Seasonal' }
];
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`Successfully updated ${OUTPUT_FILE}`);

} catch (err) {
    console.error('Error generating gallery:', err);
    process.exit(1);
}
