// Gallery Data Management
// This file is auto-generated by scripts/generate-gallery.js
// Do not edit manually if you plan to use the script.

export interface GalleryImage {
  id: number;
  filename: string;
  title: string;
  description: string;
  category: 'luxury' | 'classic' | 'modern' | 'artistic' | 'seasonal';
  featured?: boolean;
  tags?: string[];
  dateAdded?: string;
}

export const galleryImages: GalleryImage[] = [
  {
    "id": 1,
    "filename": "artistic-floral-design.jpeg",
    "title": "Artistic Floral Design",
    "description": "Artistic Floral Design - Professional nail art design",
    "category": "artistic",
    "featured": true,
    "tags": [
      "artistic",
      "floral"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 2,
    "filename": "bold-statement-nails.jpeg",
    "title": "Bold Statement Nails",
    "description": "Bold Statement Nails - Professional nail art design",
    "category": "artistic",
    "featured": true,
    "tags": [
      "artistic",
      "bold"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 3,
    "filename": "classic-nude-elegance.jpeg",
    "title": "Classic Nude Elegance",
    "description": "Classic Nude Elegance - Professional nail art design",
    "category": "classic",
    "featured": true,
    "tags": [
      "classic",
      "nude"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 4,
    "filename": "classic-nude-nail-art.png",
    "title": "Classic Nude Nail Art",
    "description": "Classic Nude Nail Art - Professional nail art design",
    "category": "classic",
    "featured": true,
    "tags": [
      "classic",
      "nude"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 5,
    "filename": "elegant-french-tips.jpeg",
    "title": "Elegant French Tips",
    "description": "Elegant French Tips - Professional nail art design",
    "category": "classic",
    "featured": true,
    "tags": [
      "classic",
      "french"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 6,
    "filename": "floral-design-nail-art.png",
    "title": "Floral Design Nail Art",
    "description": "Floral Design Nail Art - Professional nail art design",
    "category": "artistic",
    "featured": true,
    "tags": [
      "artistic",
      "floral"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 7,
    "filename": "french-tips-nail-art.png",
    "title": "French Tips Nail Art",
    "description": "French Tips Nail Art - Professional nail art design",
    "category": "classic",
    "featured": false,
    "tags": [
      "classic",
      "french"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 8,
    "filename": "geometric-modern-nail-art.png",
    "title": "Geometric Modern Nail Art",
    "description": "Geometric Modern Nail Art - Professional nail art design",
    "category": "modern",
    "featured": false,
    "tags": [
      "modern",
      "geometric"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 9,
    "filename": "glamorous-sparkle.jpeg",
    "title": "Glamorous Sparkle",
    "description": "Glamorous Sparkle - Professional nail art design",
    "category": "artistic",
    "featured": false,
    "tags": [
      "artistic",
      "sparkle"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 10,
    "filename": "gold-accent-nail-art.png",
    "title": "Gold Accent Nail Art",
    "description": "Gold Accent Nail Art - Professional nail art design",
    "category": "luxury",
    "featured": false,
    "tags": [
      "luxury",
      "gold"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 11,
    "filename": "luxury-gold-accent.jpeg",
    "title": "Luxury Gold Accent",
    "description": "Luxury Gold Accent - Professional nail art design",
    "category": "luxury",
    "featured": false,
    "tags": [
      "luxury",
      "gold"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 12,
    "filename": "main-hero-nail-art.png",
    "title": "Main Hero Nail Art",
    "description": "Main Hero Nail Art - Professional nail art design",
    "category": "artistic",
    "featured": false,
    "tags": [
      "artistic"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 13,
    "filename": "modern-geometric-pattern.jpeg",
    "title": "Modern Geometric Pattern",
    "description": "Modern Geometric Pattern - Professional nail art design",
    "category": "modern",
    "featured": false,
    "tags": [
      "modern",
      "geometric"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 14,
    "filename": "premium-ombre-design.jpeg",
    "title": "Premium Ombre Design",
    "description": "Premium Ombre Design - Professional nail art design",
    "category": "artistic",
    "featured": false,
    "tags": [
      "artistic",
      "ombre"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 15,
    "filename": "textured-matte-nail-art.png",
    "title": "Textured Matte Nail Art",
    "description": "Textured Matte Nail Art - Professional nail art design",
    "category": "artistic",
    "featured": false,
    "tags": [
      "artistic",
      "matte"
    ],
    "dateAdded": "2025-12-25"
  },
  {
    "id": 16,
    "filename": "updated-hero-nail-art.png",
    "title": "Updated Hero Nail Art",
    "description": "Updated Hero Nail Art - Professional nail art design",
    "category": "artistic",
    "featured": false,
    "tags": [
      "artistic"
    ],
    "dateAdded": "2025-12-25"
  }
];

// Helper functions for gallery management
export const getImagePath = (filename: string): string => {
  return `${process.env.PUBLIC_URL}/assets/images/gallery/${filename}`;
};

export const getFeaturedImages = (): GalleryImage[] => {
  return galleryImages.filter(image => image.featured);
};

export const getImagesByCategory = (category: string): GalleryImage[] => {
  if (category === 'all') return galleryImages;
  return galleryImages.filter(image => image.category === category);
};

export const getImagesByTag = (tag: string): GalleryImage[] => {
  return galleryImages.filter(image =>
    image.tags?.includes(tag.toLowerCase())
  );
};

export const getRecentImages = (count: number = 6): GalleryImage[] => {
  // Since we don't have real dates in filenames, we just take the last added (highest ID) or just logic from array
  return [...galleryImages].reverse().slice(0, count);
};

export const galleryCategories = [
  { value: 'all', label: 'All Designs' },
  { value: 'luxury', label: 'Luxury' },
  { value: 'classic', label: 'Classic' },
  { value: 'modern', label: 'Modern' },
  { value: 'artistic', label: 'Artistic' },
  { value: 'seasonal', label: 'Seasonal' }
];
